[project]
name = "mythesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "nibabel>=5.3.3",
    "pydantic>=2.12.5",
    "pydicom>=3.0.1",
    "scikit-learn>=1.8.0",
]
